services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: Bandung@2026
      POSTGRES_DB: forumapi
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U developer -d forumapi"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
